[options]
packages = find:
include-package-data = True

[options.packages.find]
where = .
include =
    pyffi*
    scripts*

[metadata]
license_file = LICENSE.rst

[pep8]
# line length
ignore=E501

[coverage:run]
source = pyffi

[tool:pytest]
addopts =
    --verbose
    --import-mode=importlib
    --ignore tests/perf
    --ignore pyffi/formats/cgf
    --ignore pyffi/formats/dae
    --ignore pyffi/formats/esp
    --ignore pyffi/object_models/xsd
    --ignore pyffi/qskope
    --cov=pyffi
    --cov=scripts
    --cov-report term-missing
    --cov-report html:htmlcov
log_file = tests/pytest.log
testpaths = pyffi tests
doctest_optionflags = ELLIPSIS NORMALIZE_WHITESPACE REPORT_NDIFF
doctest_plus = enabled